### ISSUE TITLE
大佬你好，我在阅读代码中有一个疑问。

### ISSUE THREAD

**Issue by luzhouWH** [bubbliiiing/yolov4-tiny-pytorch#100]
在nets的CSPdarknet53_tiny.py的class Resblock_body(nn.Module)其中的def forward(self, x)。
您使用route = x的复制，但是在python中这样好像是给的x的地址，后续x变化的话，route 也会跟着变化，达不到残差的效果了。
请问这里需不需要改写成深度复制？

**Comment by bubbliiiing** [comment]
你可以看看route 和x的值0 0，应该没有这个问题

**Comment by luzhouWH** [comment]
刚刚看了，真的不一样。非常感谢大佬。
