### ISSUE TITLE
解码bbox问题

### ISSUE THREAD

**Issue by LLLiu123** [bubbliiiing/yolov4-tiny-pytorch#103]
大佬你好，请问yolov4-tiny使用的nms是什么呢，在utils_bbox中有两个类---decodebox和decodeboxnp。两个类下，都定义了nms,是组合使用的吗？我将decodeboxnp注释掉后，似乎也不影响运行，所以使用的是decodebox中的nms吗？这个类中的nms直接调用了torchvision中的函数，请问yolov4-tiny官方是用的这种nms吗。

**Comment by bubbliiiing** [comment]
额就是普通的nms呀，torch自带的啊

**Comment by LLLiu123** [comment]
好的，谢谢答复，这个问题已经学明白了。
想请问一下，关于检测头self.balance        = [0.06,0.25,1.0,4.0]的问题，我在yolov4-tiny上添加了两个检测头，结果模型的泛化能力极差，请问是不是这个balance值的问题?在网上查相关的资料，是这样设置的系数 [0.06,0.25,1.0,4.0]，0.06是13x13检测头的，依次类推4.0是大特征图检测头的。这个balance是如何影响网络的性能的呢，是不是系数越大，越关注该检测头的loss?这个值又是如何设置的呢？

**Comment by bubbliiiing** [comment]
额……你的anchors如何设置？

**Comment by LLLiu123** [comment]
谢谢答复，通过增加迭代次数，解决了，可能因为，增加检测头，网络深度增加，需要更多的迭代次数。
