### ISSUE TITLE
get_map问题

### ISSUE THREAD

**Issue by LLLiu123** [bubbliiiing/yolov4-tiny-pytorch#106]
大家有没有遇到,同样的权重，相关的系数也都设置的一样同样的测试集，测的map却不一样的问题。我用map_vis时，报错没有发现id，但test.txt里面根本就没有这个id。

**Comment by bubbliiiing** [comment]
get_map是因为每次权值初始化不一样导致的欸0

**Comment by bubbliiiing** [comment]
你应该是map out没删除

**Comment by LLLiu123** [comment]
是的，已经发现这个问题了，谢谢
