### ISSUE TITLE
How to evaluate .weights  map here

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [bubbliiiing/yolov4-tiny-pytorch#17]
Hi,  I have trained yolov4-tiny using darknet repo, Now I have .weights and .cfg ,  Now I have two questions. 

1- How I can calculate the Precision and recall for each class using .weights? do  I need to convert .wegiths to .pt first? if yes then I can convert? 

2- Can I convert .weights to .caffe?

**Comment by bubbliiiing** [comment]
sorry, this is a pytorch repo, I don't know how to convert.
