### ISSUE TITLE
你好，val_loss为1.6，map=0是什么原因

### ISSUE THREAD

**Issue by Fafa-DL** [bubbliiiing/yolov4-tiny-pytorch#2]
用了作者YOLOv4跑出的val_loss是1.7，map=98.1%，然后今天用tiny对相同的数据集设置相同的训练参数最后map结果是0，不知道哪里有问题

**Comment by bubbliiiing** [comment]
0的话有点上头吧，你预测过有效果嘛

**Comment by Fafa-DL** [comment]
谢谢回复，已经解决，但是效果不好，只有58%

------------------ 原始邮件 ------------------
发件人: Bubbliiiing <notifications@github.com&gt;
发送时间: 2020年7月6日 15:18
收件人: bubbliiiing/yolov4-tiny-pytorch <yolov4-tiny-pytorch@noreply.github.com&gt;
抄送: Fafa-DL <516451964@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[bubbliiiing/yolov4-tiny-pytorch] 你好，val_loss为1.6，map=0是什么原因 (#2)

**Comment by bubbliiiing** [comment]
毕竟只是tiny，参数量仅500W，你可以多训练一下，也可以关闭mosaic试试

**Comment by Fafa-DL** [comment]
好的，谢谢。

------------------ 原始邮件 ------------------
发件人: Bubbliiiing <notifications@github.com&gt;
发送时间: 2020年7月6日 15:21
收件人: bubbliiiing/yolov4-tiny-pytorch <yolov4-tiny-pytorch@noreply.github.com&gt;
抄送: Fafa-DL <516451964@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[bubbliiiing/yolov4-tiny-pytorch] 你好，val_loss为1.6，map=0是什么原因 (#2)





 
毕竟只是tiny，参数量仅500W，你可以多训练一下，也可以关闭mosaic试试

**Comment by Fafa-DL** [comment]
大佬能把faster rcnn的vgg权重发我吗，百度云是真的太慢了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bubbliiiing"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 下午3:21
收件人:&nbsp;"bubbliiiing/yolov4-tiny-pytorch"<yolov4-tiny-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"邹"<516451964@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bubbliiiing/yolov4-tiny-pytorch] 你好，val_loss为1.6，map=0是什么原因 (#2)





 
毕竟只是tiny，参数量仅500W，你可以多训练一下，也可以关闭mosaic试试

**Comment by Jasonshao0123** [comment]
请问map=0是怎么解决的呢？我替换了主干，修改了主干，训练之后loss=0.18，但是map为0

**Comment by bubbliiiing** [comment]
没有预训练吧
