### ISSUE TITLE
The mask index of anchors 

### ISSUE THREAD

**Issue by eric612** [bubbliiiing/yolov4-tiny-pytorch#25]
I'm confused of the [maske index](https://github.com/bubbliiiing/yolov4-tiny-pytorch/blob/master/nets/yolo_training.py#L362) , is it should be 
anchor_index = [[3,4,5],[0,1,2]][self.feature_length.index(in_w)] ?

**Comment by happyboyneu** [comment]
我也发现了这个问题，issue为什么关闭了？应该是这个版本吧anchor_index = [[3,4,5],[0,1,2]]？

**Comment by bubbliiiing** [comment]
视频说了噢。
