### ISSUE TITLE
train.py脚本中的fit_one_epoch入参是不是有问题？

### ISSUE THREAD

**Issue by happy2019-k** [bubbliiiing/yolov4-tiny-pytorch#38]
def fit_one_epoch(net,yolo_losses,epoch,epoch_size,epoch_size_val,gen,genval,Epoch,cuda):其中yolo_losses参数在后边并没有使用，而使用的是yolo_loss，这个地方是不是有问题？

**Comment by happy2019-k** [comment]
@bubbliiiing

**Comment by bubbliiiing** [comment]
忘了改变量名，不影响训练的。
