### ISSUE TITLE
YOLOv4-tiny的參數量(parameter)

### ISSUE THREAD

**Issue by 108368062** [bubbliiiing/yolov4-tiny-pytorch#43]
您好，請問要怎麼得到YOLOv4-tiny的參數量(parameter)呢?謝謝
類似以下網址這種，請問程式碼中的「model」要改成甚麼，並且可以在哪一個程式碼加入，謝謝
https://stackoverflow.com/questions/49201236/check-the-total-number-of-parameters-in-a-pytorch-model

**Comment by bubbliiiing** [comment]
test.py 可以获得吧

**Comment by 108368062** [comment]
謝謝，可以了
