### ISSUE TITLE
计算FPS的py文件

### ISSUE THREAD

**Issue by guoshu-cpu** [bubbliiiing/yolov4-tiny-pytorch#53]
你好博主，之前有看到别人复现你的yolov4-tiny代码，里面有个FPS-test.py的代码算FPS，为什么现在没有看见呀

**Comment by guoshu-cpu** [comment]
哎，不好意思，我刚看见你写的predit.py里面可以测试fps

**Comment by guoshu-cpu** [comment]
不过只能处理一张图片的fps，那我要是处理voctest的4952张图片。需要怎么修改呢？？？

**Comment by bubbliiiing** [comment]
emm0 0
