### ISSUE TITLE
训练时发现LOSS值异常的小（第一轮是2.多，第二轮就是0.001以下了）

### ISSUE THREAD

**Issue by RuidongDavidLin** [bubbliiiing/yolov4-tiny-pytorch#80]
大佬，我用的最新一版的代码训练，在使用自己的训练集训练时，发现loss值异常的小，然后训练完之后也检测不出任何物品（我也把confidence调到了0.01，也是无法检测），然后我用之前的旧版代码训练时，却没有这个问题，这是为什么呢

**Comment by RuidongDavidLin** [comment]
使用的都是大佬的默认参数

**Comment by bubbliiiing** [comment]
解决了？

**Comment by RuidongDavidLin** [comment]
> 
是的，仓库里的原装代码默认参数种没有启用冻结训练，所以训练效果不好，之前一直以为是开着的，UP主可以更新一下那个参数，避免小白踩坑

**Comment by bubbliiiing** [comment]
emm…………事实上……在voc里，关闭冻结效果更好……

**Comment by RuidongDavidLin** [comment]
> emm…………事实上……在voc里，关闭冻结效果更好……

这样啊，可能voc数据集量比较大，我们自己训练的时候一般都是只用100-200张每个类别的识别，任务比较简单，所以收敛效果不好吧

**Comment by bubbliiiing** [comment]
对，小数据量……也不合适，确实没办法，不同人的情况不一样0 0。

**Comment by RuidongDavidLin** [comment]
> 对，小数据量……也不合适，确实没办法，不同人的情况不一样0 0。

嗯嗯，谢谢大佬了！
