### ISSUE TITLE
请问您可以上传weights去google drive吗？

### ISSUE THREAD

**Issue by MheadHero** [bubbliiiing/yolov4-tiny-pytorch#85]
你好 我是来自在马来西亚的粉丝 发现到你的yolov4 想要试试用 但是weight 我用不到百度盘来下载 所以希望你可以上传去google drive 拜托您了！

**Comment by bubbliiiing** [comment]
你直接点那个性能情况里面的链接，从github下载

**Comment by MheadHero** [comment]
哦哦哦 我会了 谢谢你！不过我真的没想到你会那么快回复！ 谢谢你！！

**Comment by bubbliiiing** [comment]
好的，现在在摸鱼…正好看到了就回复了
